[package]
name = "bin-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bin"
path = "src/main.rs"

[dependencies]
configparser = "3.1.0"
nix = { version = "0.30.1", features = ["process"] }
os_str_bytes = "7.1.0"
