blank_issues_enabled: true

contact_links:

  - name: Suggest a new feature
    url: https://github.com/bin-cli/bin-cli/discussions/new?category=feature-suggestions-requests
    about: Share ideas for new features in Bin CLI.

  - name: Ask for help
    url: https://github.com/bin-cli/bin-cli/discussions/new?category=help-requests
    about: Get help with Bin CLI (or Bash scripting in general).

  - name: Share script-writing tips & example scripts
    url: https://github.com/bin-cli/bin-cli/discussions/new?category=script-writing-tips-example-scripts
    about: Share your own scripts, tips, best practices, etc.

  - name: Share alternatives to Bin CLI
    url: https://github.com/bin-cli/bin-cli/discussions/new?category=alternatives-to-bin-cli
    about: Discuss the pros and cons of Bin CLI vs its competitors.

  - name: Meta discussion
    url: https://github.com/bin-cli/bin-cli/discussions/categories/meta-discussion
    about: Issue category missing? Development process could be improved?
