name: Release to GitHub

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Release (1.2.3)
      - 'v[0-9]+.[0-9]+.[0-9]+-*' # Prerelease (1.2.3-alpha.1)

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y debmake equivs rpm
          sudo mk-build-deps -ir debian/control
          rm -f *.changes

      - name: Build DEB package
        run: |
          bin/generate/deb "${GITHUB_REF_NAME/v}"
          mv dist /tmp/dist-deb

      - name: Build RPM package
        run: |
          bin/generate/rpm "${GITHUB_REF_NAME/v}"
          mv dist /tmp/dist-rpm

      - name: Create GitHub Draft Release
        uses: crowbarmaster/GH-Automatic-Releases@d01f8167e06547c06e2a94267e378e7ca513e3ec # v1.6.0
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          draft: true
          prerelease: "${{ contains(github.ref_name, '-') }}"
          files: |
            /tmp/dist-deb/bin
            /tmp/dist-deb/bin.1.gz
            /tmp/dist-deb/binconfig.5.gz
            /tmp/dist-deb/bin-cli.deb
            /tmp/dist-rpm/bin-cli.rpm
