version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: quarterly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: quarterly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: quarterly
