name: Deploy to GitHub Pages

on:
  release:
    types: [released]
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  generate:
    name: Generate Pages
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Set the version number
        run: echo "${GITHUB_REF_NAME/v}" > VERSION

      - name: Generate Pages
        run: make pages

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: temp/dist

  deploy:
    name: Deploy to GitHub Pages
    needs: generate
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      pages: write
    steps:
       - name: Deploy to GitHub Pages
         uses: actions/deploy-pages@v4
