name: Deploy to GitHub Pages

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  generate:
    name: Generate Pages
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Generate HTML man pages
        env:
          version: "${{ inputs.version || github.ref_name }}"
        run: bin/generate/man-html "${version/v}"

      - name: Generate HTML readme
        run: bin/generate/readme-html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: dist

  deploy:
    name: Deploy to GitHub Pages
    needs: generate
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      pages: write
    steps:
       - name: Deploy to GitHub Pages
         uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
