name: Deploy to GitHub Pages

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

concurrency:
  group: '${{ github.workflow }}'
  cancel-in-progress: true

env:
  FORCE_COLOR: 1

jobs:
  generate:
    name: Generate Pages
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Generate HTML man pages
        env:
          version: "${{ inputs.version || github.ref_name }}"
        run: bin/generate/man-html "${version/v}"

      - name: Generate HTML readme
        run: bin/generate/readme-html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    name: Deploy to GitHub Pages
    needs: generate
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      pages: write
    steps:
       - name: Deploy to GitHub Pages
         uses: actions/deploy-pages@v4
