name: Release to GitHub

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Release (1.2.3)
      - 'v[0-9]+.[0-9]+.[0-9]+-*' # Prerelease (1.2.3-alpha.1)

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Set the version number
        run: echo "${GITHUB_REF_NAME/v}" > VERSION

      - name: Build package
        run: make bin man

      - name: Create GitHub Draft Release
        uses: crowbarmaster/GH-Automatic-Releases@v1.6.0
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          draft: true
          prerelease: "${{ contains(github.ref_name, '-') }}"
          files: |
            temp/dist/bin
            temp/dist/bin.1.gz
            temp/dist/binconfig.5.gz
