name: Update README

on:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  generate-readme:
    name: Generate README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: '${{ github.head_ref }}'

      - name: Install Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install JavaScript packages
        run: npm ci

      - name: Generate README
        run: bin/generate/readme

      # This doesn't do anything if the README didn't change
      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
        with:
          file_pattern: README.md
          commit_message: Generate README

      - name: Check links
        run: bin/check-readme-links || echo '::warning::One or more links appear to be broken.'
