name: Update README

on:
  pull_request:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  generate-readme:
    name: Generate README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: '${{ github.head_ref }}'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install JavaScript packages
        run: npm ci

      - name: Generate README
        run: make readme

      # This doesn't do anything if the README didn't change
      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: README.md
          commit_message: Generate README

      # This is *after* the commit/push because it's not critical if there
      # are broken links - it's better to have the correct information
      - name: Check links
        run: bin/check-readme-links
